c:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.c'
      - '**/*.h'
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - .github/CODEOWNERS
      - LICENSE
github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*.yml
submodules:
  - changed-files:
    - any-glob-to-any-file:
      - externals/*
